//
//  Fare.swift
//  MRT Fares
//
//  Created by Shawn Law on 12/10/2024.
//

import Foundation

struct Fare: Identifiable, Hashable {
    let id = UUID()
    let name: String
    let price: Double
}


let dummyFares: [Fare] = [
    Fare(name: "16 Sierra", price: 4.56),
    Fare(name: "Abdullah Hukum", price: 4.56),
    Fare(name: "Alam Megah", price: 4.56),
    Fare(name: "Alam Sutera", price: 4.56),
    Fare(name: "Ampang", price: 4.56),
    Fare(name: "Ampang Park", price: 4.56),
    Fare(name: "Ampang Park (MRT)", price: 4.56),
    Fare(name: "Ara Damansara", price: 4.56),
    Fare(name: "Asia Jaya", price: 4.56),
    Fare(name: "Awan Besar", price: 4.56),
    Fare(name: "Bandar Puteri", price: 4.56),
    Fare(name: "Bandar Tasik Selatan", price: 4.56),
    Fare(name: "Bandar Tun Hussein Onn", price: 4.56),
    Fare(name: "Bandar Tun Razak", price: 4.56),
    Fare(name: "Bandar Utama", price: 4.56),
    Fare(name: "Bandaraya", price: 4.56),
    Fare(name: "Bangsar", price: 4.56),
    Fare(name: "Batu 11 Cheras", price: 4.56),
    Fare(name: "Bukit Bintang", price: 4.56),
    Fare(name: "Bukit Bintang (MRL)", price: 4.56),
    Fare(name: "Bukit Dukung", price: 4.56),
    Fare(name: "Bukit Jalil", price: 4.56),
    Fare(name: "Bukit Nanas", price: 4.56),
    Fare(name: "Cahaya", price: 4.56),
    Fare(name: "Cempaka", price: 4.56),
    Fare(name: "Chan Show Lin (MRT)", price: 4.56),
    Fare(name: "Chan Sow Lin", price: 4.56),
    Fare(name: "Cheras", price: 4.56),
    Fare(name: "Chow Kit", price: 4.56),
    Fare(name: "Cochrane", price: 4.56),
    Fare(name: "Conlay", price: 4.56),
    Fare(name: "Cyberjaya City Centre", price: 4.56),
    Fare(name: "Cyberjaya Utara", price: 4.56),
    Fare(name: "Damai", price: 4.56),
    Fare(name: "Damansara Damai", price: 4.56),
    Fare(name: "Dang Wangi", price: 4.56),
    Fare(name: "Dato Keramat", price: 4.56),
    Fare(name: "Glenmarie", price: 4.56),
    Fare(name: "Gombak", price: 4.56),
    Fare(name: "Hang Tuah", price: 4.56),
    Fare(name: "Hang Tuah (MRL)", price: 4.56),
    Fare(name: "Hospital Kuala Lumpur", price: 4.56),
    Fare(name: "Imbi", price: 4.56),
    Fare(name: "IOI Puchong", price: 4.56),
    Fare(name: "Jalan Ipoh", price: 4.56),
    Fare(name: "Jelatek", price: 4.56),
    Fare(name: "Jinjang", price: 4.56),
    Fare(name: "Kajang", price: 4.56),
    Fare(name: "Kampung Baru", price: 4.56),
    Fare(name: "Kampung Batu", price: 4.56),
    Fare(name: "Kampung Selamat", price: 4.56),
    Fare(name: "Kelana Jaya", price: 4.56),
    Fare(name: "Kentonmen", price: 4.56),
    Fare(name: "Kepong Baru", price: 4.56),
    Fare(name: "Kerinchi", price: 4.56),
    Fare(name: "Kinrara BK 5", price: 4.56),
    Fare(name: "KL Sentral", price: 4.56),
    Fare(name: "KL Sentral (MRL)", price: 4.56),
    Fare(name: "KLCC", price: 4.56),
    Fare(name: "Kota Damansara", price: 4.56),
    Fare(name: "Kuchai", price: 4.56),
    Fare(name: "Kwasa Damansara", price: 4.56),
    Fare(name: "Kwasa Damansara", price: 4.56),
    Fare(name: "Kwasa Sentral", price: 4.56),
    Fare(name: "Lembah Subang", price: 4.56),
    Fare(name: "Maharajalela", price: 4.56),
    Fare(name: "Maluri", price: 4.56),
    Fare(name: "Maluri", price: 4.56),
    Fare(name: "Masjid Jamek", price: 4.56),
    Fare(name: "Masjid Jamek", price: 4.56),
    Fare(name: "Medan Tuanku", price: 4.56),
    Fare(name: "Mentari", price: 4.56),
    Fare(name: "Merdeka", price: 4.56),
    Fare(name: "Metro Prima", price: 4.56),
    Fare(name: "Miharja", price: 4.56),
    Fare(name: "Muhibbah", price: 4.56),
    Fare(name: "Mutiara Damansara", price: 4.56),
    Fare(name: "Muzium Negara", price: 4.56),
    Fare(name: "Pandan Indah", price: 4.56),
    Fare(name: "Pandan Jaya", price: 4.56),
    Fare(name: "Pasar Seni", price: 4.56),
    Fare(name: "Pasar Seni", price: 4.56),
    Fare(name: "Persiaran KLCC", price: 4.56),
    Fare(name: "Phileo Damansara", price: 4.56),
    Fare(name: "Plaza Rakyat", price: 4.56),
    Fare(name: "Puchong Perdana", price: 4.56),
    Fare(name: "Puchong Prima", price: 4.56),
    Fare(name: "Pudu", price: 4.56),
    Fare(name: "Pusat Bandar Damansara", price: 4.56),
    Fare(name: "Pusat Bandar Puchong", price: 4.56),
    Fare(name: "Putra Heights", price: 4.56),
    Fare(name: "Putra Heights", price: 4.56),
    Fare(name: "Putra Permai", price: 4.56),
    Fare(name: "Putrajaya Sentral", price: 4.56),
    Fare(name: "PWTC", price: 4.56),
    Fare(name: "Raja Chulan", price: 4.56),
    Fare(name: "Raja Uda", price: 4.56),
    Fare(name: "Salak Selatan", price: 4.56),
    Fare(name: "Semantan", price: 4.56),
    Fare(name: "Sentul", price: 4.56),
    Fare(name: "Sentul Barat", price: 4.56),
    Fare(name: "Sentul Timur", price: 4.56),
    Fare(name: "Serdang Jaya", price: 4.56),
    Fare(name: "Serdang Raya Selatan", price: 4.56),
    Fare(name: "Serdang Raya Utara", price: 4.56),
    Fare(name: "Seri Raya", price: 4.56),
    Fare(name: "Setiawangsa", price: 4.56),
    Fare(name: "SMD", price: 4.56),
    Fare(name: "South Quay - USJ1", price: 4.56),
    Fare(name: "Sri Damansara Barat", price: 4.56),
    Fare(name: "Sri Damansara Sentral", price: 4.56),
    Fare(name: "Sri Damansara Timur", price: 4.56),
    Fare(name: "Sri Delima", price: 4.56),
    Fare(name: "Sri Petaling", price: 4.56),
    Fare(name: "Sri Rampai", price: 4.56),
    Fare(name: "SS 15", price: 4.56),
    Fare(name: "SS 18", price: 4.56),
    Fare(name: "Stadium Kajang", price: 4.56),
    Fare(name: "Subang Alam", price: 4.56),
    Fare(name: "Subang Jaya", price: 4.56),
    Fare(name: "Sultan Ismail", price: 4.56),
    Fare(name: "Sungai Besi", price: 4.56),
    Fare(name: "Sungai Besi (MRT)", price: 4.56),
    Fare(name: "Sungai Buloh", price: 4.56),
    Fare(name: "Sungai Jernih", price: 4.56),
    Fare(name: "SunU - Monash", price: 4.56),
    Fare(name: "Sunway - Setia Jaya", price: 4.56),
    Fare(name: "Sunway Lagoon", price: 4.56),
    Fare(name: "Surian", price: 4.56),
    Fare(name: "Taipan", price: 4.56),
    Fare(name: "Taman Bahagia", price: 4.56),
    Fare(name: "Taman Connaught", price: 4.56),
    Fare(name: "Taman Equine", price: 4.56),
    Fare(name: "Taman Jaya", price: 4.56),
    Fare(name: "Taman Melati", price: 4.56),
    Fare(name: "Taman Midah", price: 4.56),
    Fare(name: "Taman Mutiara", price: 4.56),
    Fare(name: "Taman Naga Emas", price: 4.56),
    Fare(name: "Taman Paramount", price: 4.56),
    Fare(name: "Taman Perindustrian Puchong", price: 4.56),
    Fare(name: "Taman Pertama", price: 4.56),
    Fare(name: "Taman Suntex", price: 4.56),
    Fare(name: "Taman Tun Dr Ismail", price: 4.56),
    Fare(name: "Titiwangsa", price: 4.56),
    Fare(name: "Titiwangsa (MRL)", price: 4.56),
    Fare(name: "Titiwangsa (MRT)", price: 4.56),
    Fare(name: "Tun Razak Exchange", price: 4.56),
    Fare(name: "Tun Razak Exchange", price: 4.56),
    Fare(name: "Tun Sambanthan", price: 4.56),
    Fare(name: "Universiti", price: 4.56),
    Fare(name: "UPM", price: 4.56),
    Fare(name: "USJ 21", price: 4.56),
    Fare(name: "USJ 7", price: 4.56),
    Fare(name: "USJ7 (BRT)", price: 4.56),
    Fare(name: "Wangsa Maju", price: 4.56),
    Fare(name: "Wawasan", price: 4.56),

]
